name: 👀 Linter
on:
  push:
    branches:
      - 1.x
  pull_request:
    branches:
      - 1.x
permissions:
  contents: read
jobs:
  linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./tools/github-actions/setup-deps
      - run: make tools
      - run: make lint
